server {
    listen 80;
    server_name frdb.qclub.au;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name frdb.qclub.au;

    access_log /home/frdb/access.log;
    error_log /home/frdb/nginx_error.log;

    client_max_body_size 20m;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/frdb/frdb.sock;
    }

    ssl_certificate /etc/letsencrypt/live/qclub.au/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qclub.au/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
