from __future__ import annotations

from importlib.util import module_from_spec, spec_from_file_location
import json
from pathlib import Path
import re

from .rules import BIOLOGICAL_MATERIAL_ORDER, EQUIPMENT_ORDER, RECOVERY_METHOD_ORDER, SUBSTRATE_TYPE_ORDER, row_key


def default_output_path(repo_root: Path, workbook_path: Path) -> Path:
    return repo_root / "data" / f"{module_name_from_stem(workbook_path.stem)}.py"


def module_name_from_stem(stem: str) -> str:
    name = re.sub(r"\W+", "_", stem.lower()).strip("_")
    if not name:
        raise ValueError("Workbook name does not contain a usable module name")
    if name[0].isdigit():
        name = f"workbook_{name}"
    return name


def merge_existing_rows(output_path: Path, generated_rows: list[dict]) -> list[dict]:
    existing_rows = load_existing_rows(output_path)
    existing_by_key = {}
    for row in existing_rows:
        if row.get("row_key"):
            existing_by_key[row["row_key"]] = row
        if row.get("authors"):
            existing_by_key[row_key(row["authors"], row.get("source_url", ""))] = row
    next_id = max((row.get("id", 0) for row in existing_rows), default=0) + 1
    merged = []

    for row in generated_rows:
        existing = existing_by_key.get(row["row_key"])
        if existing:
            row["id"] = existing["id"]
        else:
            row["id"] = next_id
            next_id += 1
        merged.append(row)

    return sorted(merged, key=lambda item: item["id"])


def load_existing_rows(output_path: Path) -> list[dict]:
    if not output_path.exists():
        return []

    spec = spec_from_file_location("_frdb_existing_data", output_path)
    if spec is None or spec.loader is None:
        raise ValueError(f"Could not load existing data module: {output_path}")
    module = module_from_spec(spec)
    spec.loader.exec_module(module)
    return list(getattr(module, "ROWS", []))


def write_data_module(output_path: Path, workbook_path: Path, rows: list[dict]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    source = workbook_path.name
    rows_json = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    content = [
        "# Generated by script/analyze_workbook.py. Do not edit by hand.",
        "import json",
        f"SOURCE_WORKBOOK = {source!r}",
        f"FILTERS = {filters()!r}",
        f"ROWS = json.loads({rows_json!r})",
        "",
    ]
    output_path.write_text("\n".join(content), encoding="utf-8")


def filters() -> dict[str, list[str]]:
    return {
        "recovery_methods": list(RECOVERY_METHOD_ORDER),
        "equipment_tested": list(EQUIPMENT_ORDER),
        "biological_material": list(BIOLOGICAL_MATERIAL_ORDER),
        "substrate_type": list(SUBSTRATE_TYPE_ORDER),
    }
